### ISSUE TITLE
Eset Anti Virus 

### ISSUE THREAD

**Issue by 3773** [chmichael/HeliumMonitor#1]
﻿Log
C:\Program Files\Helium Monitor\Helium.Monitor.exe - eine Variante von Win64/Packed.VMProtect.J verdächtige Datei - durch Löschen gesäubert [1]

Eset Anti Virus says the Virus / Troajans ???
![Minitor](https://user-images.githubusercontent.com/4408333/172054840-d8d8954c-ee94-4051-a8cd-94d1ad2630dc.PNG)

**Comment by chmichael** [comment]
Hello,
  It's a false alarm from eset: https://www.virustotal.com/gui/file/f97f1eb42b3db243d8eeacc77b18ea60e506f6f1b814028b122912a353e373c8?nocache=1

  Although the executable is packed and protected due some people want to hack it instead donate 1 HNT! 
  
  Thank you
